# Generated by Django 4.1.7 on 2023-04-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=255)),
                ('signature_mode', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_board.boardmember')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('board_members', models.ManyToManyField(through='visual_board.BoardMembership', to='visual_board.boardmember')),
            ],
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_board.company'),
        ),
    ]
