# Generated by Django 4.2 on 2023-04-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='name_and_surname',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='signature_mode',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='status',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
